"""add note_image table

Revision ID: 767891103d02
Revises: fccd8fc539e6
Create Date: 2025-07-21 18:43:09.398661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '767891103d02'
down_revision = 'fccd8fc539e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=140), nullable=True),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.Column('note_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['note_id'], ['note.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_column('ocr_text')
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.VARCHAR(length=140), nullable=True))
        batch_op.add_column(sa.Column('ocr_text', sa.TEXT(), nullable=True))

    op.drop_table('note_image')
    # ### end Alembic commands ###
