"""add ocr_text to note table

Revision ID: fccd8fc539e6
Revises: 53a7d665a3dd
Create Date: 2025-07-02 19:50:14.296359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fccd8fc539e6'
down_revision = '53a7d665a3dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ocr_text', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_column('ocr_text')

    # ### end Alembic commands ###
